# Select language
language: python

# Select python version
python:
 - "2.7"

# Select OS
os:
 - "linux"

# Install requirements
install:
 - "pip install --upgrade setuptools"

# Run
script:
- "python Modules/__travis_test__.py"
